In [2]:
import numpy as np

In [3]:
print(np.__version__)

2.3.5


In [4]:
list = [1,2,3] *2

In [5]:
print(list)

[1, 2, 3, 1, 2, 3]


In [6]:
temperature = [33.2,44.4,31.4,40.2,26.23]

total = 0
for i in temperature:
    total = total + i
average = total/len(temperature)
print(average)

35.086


In [7]:
#numpy is superior to python list

In [8]:
temperature = np.array([33.2,44.4,31.4,40.2,26.23])
average = np.mean(temperature)
print(average)

35.086


In [9]:
array = np.array([1,2,3,4])
print(type(array))
print(array)

<class 'numpy.ndarray'>
[1 2 3 4]


In [10]:
array = array * 2

In [11]:
print(array)

[2 4 6 8]


In [12]:
# 2d arrays

In [56]:
array2d = np.array([[1,2,3],[4,5,6]])
print(array2d)
print("----"*10)
print(array2d.shape)

[[1 2 3]
 [4 5 6]]
----------------------------------------
(2, 3)


In [14]:
# zeros
zeros = np.zeros(4)
print(zeros)

[0. 0. 0. 0.]


In [15]:
zeros1 = np.zeros((4,4))
print(zeros1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [16]:
#ones
ones_array = np.ones((4))
print(ones_array)

[1. 1. 1. 1.]


In [17]:
ones_array1 = np.ones((2,4))
print(ones_array1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [18]:
# full function
full_array = np.full((2,2),7)
print(full_array)

[[7 7]
 [7 7]]


In [19]:
# sequence of numbers(start stop step)
seq_array = np.arange(1,10,2)
print(seq_array)

[1 3 5 7 9]


In [20]:
#identity matrix
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [56]:
# size , dtype , ndim , shape
s = [[1,2,3,4,5,6],[3,4,5,6,7,9]]
z = np.array(s)
print(np.size(z))
print(z.dtype)
print(z.ndim)
print(z.shape)

12
int64
2
(2, 6)


In [58]:
# astype data types conversion
w = np.array([1.3,23.3,4.4,5.5,65.32,6.23,7.45,8.24,9.24])
print(w)
print(w.dtype)
print("-"*12)
int_arr = w.astype(int)
print(int_arr)
print(int_arr.dtype)

[ 1.3  23.3   4.4   5.5  65.32  6.23  7.45  8.24  9.24]
float64
------------
[ 1 23  4  5 65  6  7  8  9]
int64


In [59]:
# operators
k = np.array([1,2,3])
print(k+1)
print(k*2)
print(k**k)

[2 3 4]
[2 4 6]
[ 1  4 27]


In [60]:
# aggregation functions we can say summary 
# sum mean median max min var(variance) std(standard daviation) 
t = np.array([10,20,30,40,50,60,70,80,90])
print("sum : ",np.sum(t))
print("mean : ",np.mean(t))
print("median : ",np.median(t))
print("max : ",np.max(t))
print("min : ",np.min(t))
print("variance : ",np.var(t))
print("standard deviation : ",np.std(t))

sum :  450
mean :  50.0
median :  50.0
max :  90
min :  10
variance :  666.6666666666666
standard deviation :  25.81988897471611


In [69]:
# indexing(accessing single element) and slicing(accessing multiple elements)
a = np.array([1,2,3,4,5,6,7,8,9,10,11])
print("3rd element : ",a[2])
print("from 1 to 5", a[0:5])
print("with step of 2", a[0:6:2]) # accessing every sceond element
print("with step of 2", a[::2])
print("reversing",a[::-1])

3rd element :  3
from 1 to 5 [1 2 3 4 5]
with step of 2 [1 3 5]
with step of 2 [ 1  3  5  7  9 11]
reversing [11 10  9  8  7  6  5  4  3  2  1]


In [7]:
# fancy indexing (selecting multiple elements at once)
a = np.array([1,2,3,4,5,6,7,8,9,10,11])
print(a[[0, 2, 3]])

[1 3 4]


In [10]:
# filtering data(Boolean Mastering) --> extractinf data based on conditions
a = np.array([1,2,3,4,5,6,7,8,9,10,11])
print(a[a>5])

[ 6  7  8  9 10 11]


In [16]:
# reshape--> changing dimension without changing the data ---> it returns a view  (lke 1D to 2D or 3D array)
a = np.array([1,2,3,4,5,6,7,8,9])
new_shape = a.reshape(3,3)
print(new_shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
# flattening array ---> multi dimensional to 1D      
a = np.array([[1,2,3,4,5,12],[6,7,8,9,10,11]])
print(a.ravel()) # --> view (effects the original array)
print(a.flatten()) # --> copy (does not effects the original array)

[ 1  2  3  4  5 12  6  7  8  9 10 11]
[ 1  2  3  4  5 12  6  7  8  9 10 11]


In [42]:
# insert (addinf new elements in the aray)
b = np.array([10,20,30,40,50,60,70])
print(np.insert(b,2,5))

[10 20  5 30 40 50 60 70]


In [43]:
# insert in 2d
b = np.array([[1,2],[3,4]])
print(b)
c = np.insert(b, 1 , [10,12],axis = 0)
print(c)

[[1 2]
 [3 4]]
[[ 1  2]
 [10 12]
 [ 3  4]]


In [44]:
# append (add at end)
d = np.array([12,13,14,15,16,17,18])
r = np.append(d,56)
print(r)

[12 13 14 15 16 17 18 56]


In [57]:
# concatenation of two arrays
r = np.array([12,13,14,15,16])
t = np.array([12,34,56,78])
y = np.concatenate((r,t))
print(y)

[12 13 14 15 16 12 34 56 78]


In [47]:
# removing elements 
b = np.array([10,20,30,40,50,60,70])
new_arr = np.delete(b,0)
print(new_arr)

[20 30 40 50 60 70]


In [55]:
# deleteing elements from 2D
b = np.array([[10,20,30,40],[50,60,70,80]])
print(b)
print("----"*10)
new_arr_row = np.delete(b,0,axis = 0)
print(new_arr_row)
print("----"*10)
new_arr_col = np.delete(b,0,axis = 1)
print(new_arr_col)

[[10 20 30 40]
 [50 60 70 80]]
----------------------------------------
[[50 60 70 80]]
----------------------------------------
[[20 30 40]
 [60 70 80]]


In [62]:
# stacking --> vertical stacking and horizontal stacking (vstack and hstack) for merging arrays horizontally or vertically
r = np.array([12,13,14,15,16])
t = np.array([12,34,56,78,20])
d = np.vstack((r,t))
print(d)
print("----"*10)
d = np.hstack((r,t))
print(d)

[[12 13 14 15 16]
 [12 34 56 78 20]]
----------------------------------------
[12 13 14 15 16 12 34 56 78 20]


In [71]:
# splitting
g = np.array([1,2,3,4,5,6,7,8])
f = np.split(g,2)
print(f)

[array([1, 2, 3, 4]), array([5, 6, 7, 8])]


In [78]:
# broadcasting
prices = [100,200,300]
discount = 0.1  # 10% discount
final_discounted_prices = []

for price in prices:
    final_price = price - (price*discount)
    final_discounted_prices.append(final_price)
print(final_discounted_prices)

[90.0, 180.0, 270.0]


In [80]:
# broadcasting- now what if we have million numbers of data then definitely using loop is a headache
prices = np.array([100,200,300])
discount = 0.1  # 10% discount
final_discounted_prices = prices - (prices*0.1)
print(final_discounted_prices)

[ 90. 180. 270.]


In [88]:
# broadcasting through single value , 2D array
prices = np.array([100,200,300])
result = prices * 2
print(result)
print("----"*10)

matrix = np.array([[1,2,3],[4,5,6]])
vector = np.array([10,20,30])
result = matrix + vector
print(result)

[200 400 600]
----------------------------------------
[[11 22 33]
 [14 25 36]]


In [89]:
# vectorization for matrix operations
matrix1 = np.array([[1,2,3],[4,5,6]])
matrix2 = np.array([[1,2,3],[4,5,6]])
result = matrix1 + matrix2
print(result)

[[ 2  4  6]
 [ 8 10 12]]


In [5]:
# handling missing values 
# np.isnan --> detects missing value, detects if someething is dividing by 0 etc
# np.nan_to_num()
# np.isinf() --> to detect infinite value
arr = np.array([64,np.nan,70,np.nan,59,78])
print(arr)
print(np.isnan(arr))

[64. nan 70. nan 59. 78.]
[False  True False  True False False]


In [8]:
# replacing nan value using nan_to_num
clean_arr = np.nan_to_num(arr,nan = np.nanmean(arr))
print(clean_arr)

[64.   67.75 70.   67.75 59.   78.  ]


In [19]:
# infinity np.isinf(arr)  finds is there any infinite value etc or not returns a boolean value 
arr1 = np.array([1,2,np.inf,3,-np.inf,10])
find_inf = np.isinf(arr1)
print(find_inf)
# replacing isinf value 
clean_arr = np.nan_to_num(arr1, posinf = 100, neginf= -100)
print(clean_arr)

[False False  True False  True False]
[   1.    2.  100.    3. -100.   10.]
